#!/bin/bash

# Quick Sample Data Insertion Script for BLINK Module
# This script provides step-by-step instructions for inserting sample data

echo "=================================================="
echo "BLINK Sample Data Insertion Guide"
echo "=================================================="
echo ""
echo "⚠️  AUTOMATED INSERTION NOT AVAILABLE"
echo "SQL must be executed via Supabase Dashboard"
echo ""
echo "📋 FOLLOW THESE STEPS:"
echo ""
echo "1. Open Supabase Dashboard in browser:"
echo "   https://supabase.com/dashboard/project/nkyoszmtyrpdwfjxggmb"
echo ""
echo "2. Navigate to SQL Editor:"
echo "   - Click 'SQL Editor' in left sidebar"
echo "   - Click '+ New query' button"
echo ""
echo "3. Copy SQL Script:"
echo "   - Open: supabase/sample_data/blink_sample_data.sql"
echo "   - Select All (Cmd+A) and Copy (Cmd+C)"
echo ""
echo "4. Paste and Execute:"
echo "   - Paste into SQL Editor"
echo "   - Click 'Run' or press Cmd+Enter"
echo "   - Wait for success message"
echo ""
echo "5. Verify Data:"
echo "   - Go to 'Table Editor'"
echo "   - Check 'blink_quotations' → Should see 2 records"
echo "   - Check 'blink_invoices' → Should see 2 records"
echo ""
echo "6. Refresh Application:"
echo "   - Open app at localhost:5173"
echo "   - Navigate to /blink/finance/ar"
echo "   - Should see 2 AR transactions"
echo ""
echo "=================================================="
echo "Expected Data:"
echo "=================================================="
echo ""
echo "✓ Sample 1: PT Sejahtera Logistik"
echo "  - Invoice: INV-2026-001"
echo "  - Amount: Rp 94,350,000"
echo "  - Paid: Rp 50,000,000"
echo "  - Status: Sebagian (Partial)"
echo ""
echo "✓ Sample 2: CV Maju Bersama"
echo "  - Invoice: INV-2025-099"
echo "  - Amount: Rp 13,875,000"
echo "  - Paid: Rp 0"
echo "  - Status: Terlambat (Overdue)"
echo ""
echo "=================================================="
echo ""
echo "Need help? Check sample_data_guide.md for details"
echo ""
